services:
  frontend:
    build:
      context: .
      args:
        # This value is passed to the Dockerfile during the build
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000/api/v1}
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # This value is available inside the container at runtime
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000/api/v1}
