import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import TanStackQueryWrapper from "./components/setupComponents/tanstackQuery/tanstackWrapper";
import { ThemeProvider } from "./components/setupComponents/ThemeProvider";
import TopProgressBarProvider from "./components/setupComponents/TopProgressBar/ProgressProvider";
import { TooltipProvider } from "./components/ui/tooltip";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <TanStackQueryWrapper>
            <TopProgressBarProvider>
              <TooltipProvider>{children}</TooltipProvider>
            </TopProgressBarProvider>
          </TanStackQueryWrapper>
        </ThemeProvider>
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 3000,
            style: {
              background: "var(--background)",
              color: "var(--foreground)",
              border: "1px solid var(--border)",
            },
          }}
        />
      </body>
    </html>
  );
}
